server.port: 7005
services:
  course:
    base-url: http://localhost:7002
  recommendation:
    base-url: http://localhost:7003
  review:
    base-url: http://localhost:7004
spring.application.name: course-composite-service
---
spring.config.activate.on-profile: docker
server.port: 8080